### ISSUE TITLE
Default locale without prefix, is it possible?

### ISSUE THREAD

**Issue by vladshoob** [codezero-be/laravel-localized-routes#1]
Hi there.

I am struggling to manage my issue. What I need is to have these routes available:

`
    /contacts - for default english,
    /uk/contacts - for ukrainian,
    etc... 
`

Maybe some hints?

**Comment by mark1282** [comment]
I'm wondering the same. For now I've just duplicated the routes so I have the localised English and non localised default. If I get chance I'll have a look through the source code.

**Comment by ivanvermeyen** [comment]
Hi,

Sorry I forgot about this issue. 

This is not the way this package currently works.
You can define normal routes, for example a home page with language selection and then localized URL's that have a prefix. When you generate a URL, the normal routes have priority over the localized ones if the route name is the same.

However, if we add an option like `omit_prefix_for_locale  = 'en';` and we do some `if` checks against the current locale in certain places to generate the correct routes and URL's, I think it is possible.

If you have time to look into this, that would be much appreciated.
If not, I will see if I can get to this any time soon.

Thanks,
Ivan

**Comment by vladshoob** [comment]
> I'm wondering the same. For now I've just duplicated the routes so I have the localised English and non localised default. If I get chance I'll have a look through the source code.

I ended up using another package: https://github.com/mcamara/laravel-localization .

**Comment by LuizTNB** [comment]
Oh, same problem here :(

@ivanvermeyen your package is good! If you solve this issue, this package will gonna be AWESOME! 

Thank you

**Comment by ivanvermeyen** [comment]
I think this [latest commit](https://github.com/codezero-be/laravel-localized-routes/commit/f75bd75e877a66a106acb978b30072c458ad9531) should do the trick.
Might need some more edge case checking.

**Comment by ivanvermeyen** [comment]
One "problematic" scenario I can think of is:

Working example that registers a root homepage and an index page for each locale:

```php
Route::localized(function () {
    // Eg. registers: '/en' and '/nl'
    Route::get('/', Controller::class.'@index')->name('index');
});

// Registers '/'
Route::get('/', Controller::class.'@index')->name('home');
```

If you omit the prefix for the main locale, you can not register the above.
But this probably makes sense, so it's a non issue?

```php
Config::set('localized-routes.omit_url_prefix_for_locale', 'en');

Route::localized(function () {
    // Eg. registers: '/' and '/nl'
    Route::get('/', Controller::class.'@index')->name('index');
});

// This URL is already registered...
Route::get('/', Controller::class.'@index')->name('home');
```

**Comment by ivanvermeyen** [comment]
Tagged in release 1.1.0 👍
