### ISSUE TITLE
Disable prefix for route names

### ISSUE THREAD

**Issue by Twyar** [codezero-be/laravel-localized-routes#110]
### From the README:
<html><body>
<p dir="auto">With supported locales <code>['en', 'nl']</code>, the above would register:</p>

URI | Name
-- | --
/en/about | en.about
/nl/about | nl.about

</body>
</html>

---

Is it somehow possible to disable this and have the routes called the same name ?

In an older Laravel 10 project I am using https://github.com/mcamara/laravel-localization and this doesn't prefix all the route names with the local names. This makes it easier for me to use in the front-end using ziggy. (Using Laravel with Inertia and Vue3).

In my old project 
```javascript
route('about')
```
Would redirect to the about page of the current selected locale.

Now that it's split up by using this page in the 2 routes states above, what's the best way I can do to achieve the same thing ?

**Comment by DonatasIk** [comment]
Hey, how did you solved this issue? Did you figure it out or just switched to another package?

**Comment by Twyar** [comment]
> Hey, how did you solved this issue? Did you figure it out or just switched to another package?

Hi,

Yeah I switched back to using the laravel-localization package of mcamara, seems to work way and way better.
