### ISSUE TITLE
Dynamic language selector

### ISSUE THREAD

**Issue by Okipa** [codezero-be/laravel-localized-routes#15]
Hi there !

First, thanks for the good work, this package is quite pleasant to use.

I managed to build a language selector which allows to navigate between language and take care of translated and static URL : I can, for example, switch from `/about` to `/a-propos`.

But I wonder how you would build a language selector which take care about the translated dynamic content.  
For example, if I take your example `Post` class with translated slugs and a route declared like this `posts/{slug}`, how would you manage to switch with a language selector from `/posts/dynamic-en-slug` to `/posts/slug-fr-dynamique`, from a post detail page, by clicking on the `FR` language flag (which the role is to send toward the exact same page translated in the targeted language)?

I imagine you already achieved this kind of things ?  
Thanks by advance !

**Comment by Okipa** [comment]
To give you a hint on how I currently manage to translate the current URL from a language to another, here is the code implemented : 

```php
route(Route::current()->getName(), Route::current()->parameters(), true, $localeKey)
````
As you can guess, it does translate the URL but not the dynamic part (the `slug` part).

**Comment by ivanvermeyen** [comment]
Hi,

I have an example of this in my demo app @ https://github.com/ivanvermeyen/test-app-laravel-localized-routes.

In the `AppServiceProvider` I added a Route macro:

```php
\Route::macro('currentUrl', function ($locale = null, $parameters = null, $absolute = true) {
    return route(\Route::currentRouteName(), $parameters ?: \Route::current()->parameters(), $absolute, $locale);
});
```

And in my views I can echo out the different URL's, passing through any parameters that should be translated. 

```php
Route::currentUrl('en', [$post])
```

Once I think the macro covers all use cases I will probably add it to this package.

Let me know if this works for your use case.

**Comment by ivanvermeyen** [comment]
With the example above, you could pass any `$parameters` to the view via the controller, like a Post view.
But on other routes you would not pass any `$parameters`.

Then you could do something like this:

```php
Route::currentUrl('en', $parameters ?? null)
```

**Comment by ivanvermeyen** [comment]
Ok... what if... `$parameters` can be a closure that accepts the requested locale?

```php
$parameters = function ($locale) {
    return [$post->getSlug($locale)];
}

return view('view.name', ['parameters' => $parameters]);
```

```php
\Route::macro('currentUrl', function ($locale = null, $parameters = null, $absolute = true) {
    if (is_callable($parameters)) {
        $parameters = $parameters($locale);
    }

    return route(\Route::currentRouteName(), $parameters ?: \Route::current()->parameters(), $absolute, $locale);
});
```

**Comment by Okipa** [comment]
@ivanvermeyen  
Good idea, thanks !  
It works, however, it feel like it is a little DIY to me.  
I wonder if it would be possible to automatize that under the hood in a `Route::currentLocalizedUrl()`.

I will try to find a way to make this possible. I you have any idea, i'll take it !

**Comment by Okipa** [comment]
Here is what I managed to do to make this work.

I updated the macro like this :

```php
Route::macro('currentLocalizedUrl', function ($locale = null, $parameters = null, $absolute = true) {
    $locale = $locale ?? app()->getLocale();
    $parameters = $parameters ?: Route::current()->parameters();
    $currentLocale = app()->getLocale();
    app()->setLocale($locale);
    foreach ($parameters as $attribute => $value) {
        if ($value instanceof Model) {
            $parameters[$attribute] = $value->getRouteKey();
        }
    }
    app()->setLocale($currentLocale);

    return route(Route::current()->getName(), $parameters, $absolute, $locale);
});
```

Which requires to have those methods declared in the `Post` model :

```php
/**
 * Get the value of the model's route key.
 *
 * @return mixed
 */
public function getRouteKey()
{
   // I use spatie/laravel-translatable package.
    return $this->getTranslation('slug', app()->getLocale());

    // without spatie/laravel-translatable package
    return $this->slug[app()->getLocale()]
}
```

```php
/**
 * Retrieve the model for a bound value.
 *
 * @param mixed $value
 *
 * @return \Illuminate\Database\Eloquent\Model|null
 */
public function resolveRouteBinding($value)
{
    return $this->where('slug->' . app()->getLocale(), $value)->firstOrFail();
}
```

And the route declared with implicit binding :

```php
Route::get(Lang::uri('posts/{post}'), [PostsController::class, 'show'])
```

If implicit binding is not configured with the `getRouteKey` and `resolveRouteBinding` methods, the translation will not fail but just render the URL with the dynamic part untranslated.

**Comment by ivanvermeyen** [comment]
Hey @Okipa 

Didn't that already work without changing the macro? (it should)

**Comment by Okipa** [comment]
Damn ! You're right, once `getRouteKey` and `resolveRouteBinding` are declared, everything is going well without this macro changes.  
I had in my mind that the `$parameters` declaration in the controller was mandatory and that's precisely the thing that I found a bit messy.  
Well, I imagine you could add it to your package then,

**Comment by ivanvermeyen** [comment]
Unless the route key is the ID, you will always need to tell Laravel what to use:
https://laravel.com/docs/6.x/routing#route-model-binding

Which isn't really that bad I think, because it is contained within the model.

The only time you need to explicitly pass the parameters, would be in the case you have something like `/en/posts/{id}/{slug?}`. Where the ID will work out of the box as it is the actual route key, but the slug is optional and is just text, so the system has no reference to how to translate it.

**Comment by Okipa** [comment]
Yes, I was well aware of that for the use of the `getRouteKeyName` method but not so much for the `resolveRouteBinding` use, which is very convenient.  

On the other hand, I didn't knew the `getRouteKey` method to customize the url value.

Thanks for your time, I keep an eye on your next releases ;)
