### ISSUE TITLE
Route::localizedUrl macro does not keep http query arguments

### ISSUE THREAD

**Issue by Okipa** [codezero-be/laravel-localized-routes#19]
Hi, it's me again ✋ 

I wonder if there would be a solution to keep URL params when using `Route::localizedUrl` ?

Currently, `/dummy?foo=bar` URL returns:
* EN:  `/en/dummy`
* FR:  `/fr/dummy`

Wouldn't be correct to keep the URL parameters in order to get:
* EN:  `/en/dummy?foo=bar`
* FR:  `/fr/dummy?foo=bar`

As URL params are not subject to translations, wouldn't it be something pretty simple to implement ?

**Comment by Okipa** [comment]
Another thought, it could also be great if eventual hash could be keep during the translation.

And... I was working on something else so I did not realized that before but, since your last releases, the routes are not translated anymore by this macro.

Will investigate a bit tomorrow in order to check why this is happening: the locale is changed but the routes segments are not translated by the macro.

`/en/news` translated with the macro gives `/fr/news` but it should return `/fr/actualites` (segments are translated).

**Comment by ivanvermeyen** [comment]
Welcome back :)

The query string and hash should be easy enough, I was already keeping this in mind but haven't implemented it yet. I'll do that asap.

The translations is something that slipped my mind tho.

The `Route::localizedUrl()` macro is no longer using the `route()` helper behind the scenes to support unnamed routes, but that means that routes with translated slugs can't be found...

Using the `route()` helper again for named routes is a partial solution, but it will still not work if routes have no name. I'll have to see what I can do about this.

**Comment by ivanvermeyen** [comment]
Query string has been [implemented](https://github.com/codezero-be/laravel-localized-routes/commit/db984c8ef7e81e386e80ccb14147d59bdf91ffe8), but apparently the hash fragment never gets sent to the backend:

https://stackoverflow.com/questions/1957030/retrieve-the-hash-in-the-url-with-php

**Comment by ivanvermeyen** [comment]
Tagged the 2.2.3 release.

This will apply the current query string to the URL generated with `Route::localizedUrl()`.

I'm still working on the ability to provide query string values via the `$parameters` array, that would replace the current query string.

It is now also possible to use `Lang::uri()` again to translate hard-coded slugs.
The only requirement is that you name the routes for this, else I see no obvious way to know which is the translated route. I also added a note in the readme for this.

**Comment by Okipa** [comment]
Hi @ivanvermeyen, sorry I finally wasn't much available today, I'm on a rush to finish this package : https://github.com/Okipa/laravel-brickables

I'll take a look about all of this tomorrow !

**Comment by ivanvermeyen** [comment]
The `Route::localizedUrl()` macro seems to be the most complicated part of this package 😄 
I hope to make the code a bit easier to digest but it's not easy with all the `if` conditionals I have to take into account.

Anyway, I tagged a new `2.2.4` release with a number of fixes/additions.

You can now provide query string parameters to the `Route::localizedUrl()` macro the same way as with the `route()` helper. If you only provide the slug parameters, then the original query string will be used.

As I mentioned earlier, the `#fragment` part of a URL is never sent to the server.
To handle that, you will need to pass the generated URL to javascript and add the `#fragment` there.

If you find more issues, don't hesitate to report and I'll jump right on 'em 👌

**Comment by Okipa** [comment]
Thanks, all seems to be good !

> If you find more issues, don't hesitate to report and I'll jump right on 'em 👌

Will do ! 👍
