### ISSUE TITLE
Map locales to custom slugs

### ISSUE THREAD

**Issue by ivanvermeyen** [codezero-be/laravel-localized-routes#20]
Add the ability to configure custom slugs values for locales, in addition to localized domains.

Maybe something in the lines of:

```php
'supported-locales' => ['en', 'nl'],

'domains' => [
    'en' => 'en.domain.test',
    'nl' => 'nl.domain.test',
],

'slugs' => [
    'en' => 'english',
    'nl' => 'dutch',
],
```

If you don't add a slug for a locale, the locale itself can be used, so it is optional.
If you don't add a domain for a locale, the default `app_url` be used, so it is optional.

**Comment by ivanvermeyen** [comment]
Also map route name prefix to locales? See #35

**Comment by mro95** [comment]
I like the idea of slugs, any progress?

**Comment by ivanvermeyen** [comment]
Not yet, as there was need for it yet.
But I can start thinking about it more seriously :)
It will take some time though, depending on the impact this has on the rest of the features.
