### ISSUE TITLE
Switch language Not set Session.

### ISSUE THREAD

**Issue by minhvn** [codezero-be/laravel-localized-routes#27]
Hi, Im have problem with:

- Im create select dropdown to change language. May be current is categories page, link change switch locale is:
* en/categories
* es/categories
* fr/categories
- When click any link above, all link on page change to locate, except homepage, after redirect to home keep locate on app/session.
I config: 'use_localizer' => true, 'use_locale_middleware' => true,
Because when click to switch language, system not set to new language, can help me.
Thank team for your project.

**Comment by ivanvermeyen** [comment]
Hi, is your homepage using the middleware?

Setting the config option for the middleware only applies to routes you register within the `Route::localized()` callback.

So for any other route you still need to apply the middleware yourself:

```php
Route::get('home', HomeController::class.'@index')
    ->middleware(\CodeZero\LocalizedRoutes\Middleware\SetLocale::class);
```

**Comment by minhvn** [comment]
> Hi, is your homepage using the middleware?
> 
> Setting the config option for the middleware only applies to routes you register within the `Route::localized()` callback.
> 
> So for any other route you still need to apply the middleware yourself:
> 
> ```
> Route::get('home', HomeController::class.'@index')
>     ->middleware(\CodeZero\LocalizedRoutes\Middleware\SetLocale::class);
> ```
HI, Im add on router, can you help me :)
```
Route::get('/', function () {
    if (Auth::check()) {
        return redirect()->action('HomeController@index');
    } else {
        return view('auth.login');
    }
});
Auth::routes();
Route::localized(function () {
    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoryController');
}
```

**Comment by ivanvermeyen** [comment]
You can add the middleware like this:

```php
Route::get('/', function () {
    if (Auth::check()) {
        return redirect()->action('HomeController@index');
    } else {
        return view('auth.login');
    }
})->middleware(\CodeZero\LocalizedRoutes\Middleware\SetLocale::class);
```

Now if you want to localize your Auth routes, you can put them inside of the `Route::localized()` callback:

```php
Route::localized(function () {
    Auth::routes();
    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoryController');
}
```

So you get `/en/login` etc.

**Comment by minhvn** [comment]
> You can add the middleware like this:
> 
> ```
> Route::get('/', function () {
>     if (Auth::check()) {
>         return redirect()->action('HomeController@index');
>     } else {
>         return view('auth.login');
>     }
> })->middleware(\CodeZero\LocalizedRoutes\Middleware\SetLocale::class);
> ```
> 
> Now if you want to localize your Auth routes, you can put them inside of the `Route::localized()` callback:
> 
> ```
> Route::localized(function () {
>     Auth::routes();
>     Route::get('home', 'HomeController@index')->name('home');
>     Route::resource('categories', 'CategoryController');
> }
> ```
> 
> So you get `/en/login` etc.

Same error, all link work perfect except homepage, click homepage will go to EN default :(

**Comment by ivanvermeyen** [comment]
Maybe it is because of this redirect:

```php
return redirect()->action('HomeController@index');
```

Can you try and redirect to the named route instead of an action?

```php
return redirect()->route('home');
```

If that doesn't work, can you `dd(app()->getLocale());` in the `/` route and see if it has the correct locale?

**Comment by minhvn** [comment]
> Maybe it is because of this redirect:
> 
> ```
> return redirect()->action('HomeController@index');
> ```
> 
> Can you try and redirect to the named route instead of an action?
> 
> ```
> return redirect()->route('home');
> ```
> 
> If that doesn't work, can you `dd(app()->getLocale());` in the `/` route and see if it has the correct locale?

Maybe on home page: url("/") and it's set back to default locale ? because "/" default is EN.

**Comment by minhvn** [comment]
I'm cheat:  <a class="navbar-brand" href="{{ url( (app()->getLocale() != 'en' ? app()->getLocale() : '') . '/home') }}">

**Comment by ivanvermeyen** [comment]
When you have `use_localizer` set to `true`, then the middleware should look for a locale in this order:

1. The URL slug
2. The session
3. A cookie
4. The browser
5. The app's default locale

So once there is a locale in the session, the homepage `/` should also pick this up...
Does your route also have the `web` middleware, so it has sessions enabled?

**Comment by minhvn** [comment]
> When you have `use_localizer` set to `true`, then the middleware should look for a locale in this order:
> 
> 1. The URL slug
> 2. The session
> 3. A cookie
> 4. The browser
> 5. The app's default locale
> 
> So once there is a locale in the session, the homepage `/` should also pick this up...
> Does your route also have the `web` middleware, so it has sessions enabled?

I'm cheat for home url {{ url( (app()->getLocale() != 'en' ? app()->getLocale() : '') . '/home') }}
:D:D

**Comment by ivanvermeyen** [comment]
Ok, it seems I didn't fully understand your question :)
Glad you figured out a solution tho! 👍 

If you want to remove the locale from the URL for all routes for your main language, then you can try this option: https://github.com/codezero-be/laravel-localized-routes#%EF%B8%8F-omit-slug-for-main-locale

Just make sure that you don't register the same route localized and non-localized:

```php
// Omit locale for all English routes:
// /home - /fr/home - /nl/home - ...
Config::set('localized-routes.omit_url_prefix_for_locale', 'en');

//Route::get('home', 'HomeController@index'); //=> Don't register this one!

Route::localized(function () {
    Route::get('home', 'HomeController@index')->name('home');
}
```

**Comment by minhvn** [comment]
> Ok, it seems I didn't fully understand your question :)
> Glad you figured out a solution tho! 👍
> 
> If you want to remove the locale from the URL for all routes for your main language, then you can try this option: https://github.com/codezero-be/laravel-localized-routes#%EF%B8%8F-omit-slug-for-main-locale
> 
> Just make sure that you don't register the same route localized and non-localized:
> 
> ```
> // Omit locale for all English routes:
> // /home - /fr/home - /nl/home - ...
> Config::set('localized-routes.omit_url_prefix_for_locale', 'en');
> 
> //Route::get('home', 'HomeController@index'); //=> Don't register this one!
> 
> Route::localized(function () {
>     Route::get('home', 'HomeController@index')->name('home');
> }
> ```

Hi bro, Im config same that, all link work good. But when I goto **"/"** maybe system set back to current language is EN. And I'm must render link **"/"** with other language.("/es/home") ...
Thank bro :)

**Comment by ivanvermeyen** [comment]
Hehe, ok ;) I'm still a bit confused but I'm happy you got it to work :)
Thanks for using the package 👍
