### ISSUE TITLE
Using localizer

### ISSUE THREAD

**Issue by loranger** [codezero-be/laravel-localized-routes#37]
Hello,

Thank you for this awesome package, but I met an issue : I can't make it work with localizer.
I have enabled the config boolean, I've also added the [localizer middleware](https://github.com/codezero-be/laravel-localizer#add-middleware) in addition to [the LocalizedRoute one](https://github.com/codezero-be/laravel-localized-routes#%EF%B8%8F-use-middleware-to-update-app-locale), but it did not work : I can't get my locale detection working.

I use the [locale switcher extension](https://chrome.google.com/webstore/detail/locale-switcher/kngfjpghaokedippaapkfihdlmmlafcc) in order to make my website work with en, fr and de. 

Even if german is detected, it's always overwritten with the default locale. I dug deeper in the localizer package and output logs (in order to avoid breaking session and cookies storage methods) from stores:

```log
[2021-04-26 13:57:45] local.DEBUG: should CodeZero\Localizer\Stores\SessionStore::store de from CodeZero\Localizer\Stores\SessionStore  
[2021-04-26 13:57:45] local.DEBUG: should CodeZero\Localizer\Stores\CookieStore::store de from CodeZero\Localizer\Stores\CookieStore  
[2021-04-26 13:57:45] local.DEBUG: should store de from CodeZero\Localizer\Stores\AppStore::store  
[2021-04-26 13:57:45] local.DEBUG: should CodeZero\Localizer\Stores\SessionStore::store en from CodeZero\Localizer\Stores\SessionStore  
[2021-04-26 13:57:45] local.DEBUG: should CodeZero\Localizer\Stores\CookieStore::store en from CodeZero\Localizer\Stores\CookieStore  
[2021-04-26 13:57:45] local.DEBUG: should store en from CodeZero\Localizer\Stores\AppStore::store  
[2021-04-26 13:57:46] local.DEBUG: from route/web.php: App::getLocale -> en  
```

What did I miss ?

**Comment by ivanvermeyen** [comment]
Hello,

If you look at the [Localizer config file](https://github.com/codezero-be/laravel-localizer/blob/master/config/localizer.php), you will find a number of detectors and stores in a specific order.
Each corresponds to a very simpel class that does the logic it needs.
The first supported / detected locale should be returned and stored in every store.

In addition, the browser locale detection is handled by [the BrowserLocale package](https://github.com/codezero-be/browser-locale) which parses the `Request::server('HTTP_ACCEPT_LANGUAGE')`. Does this have the expected locale?

https://github.com/codezero-be/browser-locale/blob/c8563bdd0fdce0e6edcce3daeda5b2fddb981f83/src/Laravel/BrowserLocaleServiceProvider.php#L28-L32

Also ensure that the 3 ServiceProviders have been discovered and any cached config is up to date.

**Comment by ivanvermeyen** [comment]
I just tried the Chrome plugin on a local project using the setup described in this packages Readme, and I did get the correct locale.

I did have to remove the cookies before reload, and also use a route that did not have a locale in the url, like `fr/some-route`. A locale in the url will always win, followed by session and cookie.

**Comment by loranger** [comment]
Thank you for your replies.

I did a step-by-step setup and realized I was not up-to-date, so I reinstall and setup everything, including the new `FallbackController` I did not call using laravel-localized-routes 2.4 and it seems to work…

Thank you so much for your support, and for your awesome and very convenient packages 👍🏻

**Comment by ivanvermeyen** [comment]
I'm happy to hear that it's working!
Thanks for the thumbs up!
