### ISSUE TITLE
Remembering preferred locale when `omit_url_prefix_for_locale` is not null

### ISSUE THREAD

**Issue by Yiddishe-Kop** [codezero-be/laravel-localized-routes#38]
Thanks for this awesome package! 👍

I'm trying to figure this out for a long time...

I have 2 locales, `['en', 'he']`. 
I set `omit_url_prefix_for_locale` to `'en'`, so the `en` locale is unprefixed.
But now whenever someone visits the default url, the locale is changed back to the default locale.

Is it possible to redirect to the previously chosen url (using the cookie/session/browser)?
In other words, if I switch to `he`, then a day later visit the default url, I should be redirected to the `he` locale.

**Comment by Yiddishe-Kop** [comment]
Thanks for pointing me in the right direction!
> and the user has no active session locale
But when the session locale is set I'll always get changed to the default locale.

My final middleware code based on your solution, I just added the `set_locale` param:
```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use CodeZero\Localizer\Stores\CookieStore;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\Route;

class SetLocale
{
    public function handle(Request $request, Closure $next)
    {
        $locale = $request->route()->getAction('localized-routes-locale');

        if (
            $locale == 'he' &&
            $request->input('set_locale') != 'he' && // I add this param to change the locale
            Cookie::get('locale') == 'en'
        ) {
            (new CookieStore)->store('en');
            return redirect(Route::localizedUrl('en'));
        }

        return $next($request);
    }
}
```

**Comment by michail1982** [comment]
i think better solution is add  detector via config, but it added at last position and you need to add App::resolving(Localizer)  in app service provider

**Comment by michail1982** [comment]
that pease of  code  save route params znd didn`t break bindings

```
        $defaultLocale = config('localized-routes.omit_url_prefix_for_locale');
        if ($request->input($key = 'set_locale') == $defaultLocale) {
            $locale = $this->localizer->detect();
            if($locale != $defaultLocale) {
                $this->localizer->store($defaultLocale);
                $params = $request->route()->parameters();
                $params[$key] = null;
                return redirect(Route::localizedUrl($defaultLocale, $params));
            }
        }
        return parent::handle($request, $next);
```
