### ISSUE TITLE
How to change $request->route()->getAction('localized-routes-locale') value to different country code?

### ISSUE THREAD

**Issue by shahmal1yev** [codezero-be/laravel-localized-routes#42]
**`$request->route()->getAction('localized-routes-locale')` return only "en". I want `omit_url_prefix_for_locale` to remain `null` and default value to "az". How to change? Please tell me the path to the source code.**

**However, it returns "en" when no country code is specified for that route and `omit_url_prefix_for_locale` is `null`.**

`omit_url_prefix_for_locale` carries two tasks. This must have been difficult for him. There must also be a parameter for "en" declared by default.

**Congratulations for the project.**

**Comment by ivanvermeyen** [comment]
Hello,

The default locale is your app locale, configured in `config/app.php`.

In the config file of this package, you have to specify all supported locales for which routes will be generated, including the default app locale.

If you define a route in the `Route::localized()` closure, it will be registered a number of times, once for each supported locale. To know which "version" of the route is for which locale, the locale is saved on the route object as a custom attribute. This can then be retrieved via `$request->route()->getAction('localized-routes-locale')`.
