### ISSUE TITLE
Error when a route has two different models with model binding

### ISSUE THREAD

**Issue by hfalucas** [codezero-be/laravel-localized-routes#54]
Hello :)

I believe I've found a limitation on this package or I'm just doing something wrong. 
My use case kinda simple, in a route with two diferent model bindings where the model implements the `ProvidesRouteParameters` when using `Route::localizedUrl()` the package just assumes the first binding and throws an error saying the 2nd parameter is missing. 

For example:
```
$router->localized(function ($router) {
    $router->get('/{foo}/{bar}', function(ModelFoo $foo, ModelBar $bar) {})
});
```

Models examples:
```
class ModelFoo extends Model implements ProvidesRouteParameters 
{
    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function getRouteParameters($locale = null)
    {
        return [$this->slug[$locale];
    }
}

class ModelBar extends Model implements ProvidesRouteParameters 
{
    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function getRouteParameters($locale = null)
    {
        return [$this->slug[$locale];
    }
}
```
The error is something like this:
```
Missing required parameter for [Route: en.route.name [URI: /{foo}/{bar}] [Missing parameter: bar].
```

Is it ok for you if I open a PR to attempt to solve this?

Thank you.

**Comment by ivanvermeyen** [comment]
Hello,

If you can pinpoint the issue and would like to submit a PR, I would of course gladly accept 👌 
I will also look into it.

Thanks for reporting this!

**Comment by hfalucas** [comment]
Hello! Thank you for such quick response. Just submitted the PR as it is easier to pinpoint the issue. Maybe there's no need for it since it's a very simple change, you can just make the changes that you feel more confortable with and reject the PR :)

**Comment by ivanvermeyen** [comment]
Thanks for the PR, that was lightning fast :)
I will merge and tag. 👍
