### ISSUE TITLE
A way to dynamicaly populate supported-locales from database ? 

### ISSUE THREAD

**Issue by azriel49** [codezero-be/laravel-localized-routes#56]
Hello,

I'm looking for a way to set the "supported-locales" configuration from db data. I can't find a way to do this properly.

Any ideas ?

**Comment by ivanvermeyen** [comment]
In theory I think it should be possible to set the `supported-locales` config option in a service provider's boot method.
I did not try this out yet though.

**Comment by ivanvermeyen** [comment]
Did you find a solution?
Closing for now but feel free to reopen.

**Comment by dnkmdg** [comment]
I was facing a similar issue, and implemented like this in `AppServiceProvider`.  
By overriding the bound settings and re-bind both `LocaleHandler` and `LocaleConfig` I was able to add my dynamically loaded locales from a custom helper. This could just as well be fetched from a database or any other source that's not available during app boot when the configs are read. 

```
        $this->app->bind(LocaleConfig::class, function ($app) {
            $config = $app['config']['localized-routes'];
            $config['supported_locales'] = LocaleHelpers::getLocales();

            return new LocaleConfig($config);
        });

        $this->app->bind('locale-config', LocaleConfig::class);

        $this->app->bind(LocaleHandler::class, function ($app) {
            $locales = $locales = $app['locale-config']->getLocales();
            $detectors = $app['config']->get('localized-routes.detectors');
            $stores = $app['config']->get('localized-routes.stores');
            $trustedDetectors = $app['config']->get('localized-routes.trusted_detectors');

            return new LocaleHandler($locales, $detectors, $stores, $trustedDetectors);
        });
```

Hope this helps someone!
