### ISSUE TITLE
Fallback Controller Invalid Route Action

### ISSUE THREAD

**Issue by liam-milbel** [codezero-be/laravel-localized-routes#61]
I am setting up this package for an existing website and I'm running into issues getting the redirects working (e.g. `/about` to `/en/about`)

I've added the following to the bottom of my `routes/web.php` file as instructed:
```php
Route::fallback(\CodeZero\LocalizedRoutes\Controller\FallbackController::class)
    ->middleware(\CodeZero\LocalizedRoutes\Middleware\SetLocale::class);
```

The problem, however, is that doing this causes Laravel to throw an error, "Invalid Route Action". It shows the error page when you visit either `/about` or `/en/about`, and even when you run `php artisan route:clear`.

I'm currently on Laravel 8, running PHP 7.4.

**Comment by liam-milbel** [comment]
I did some testing and figured out the solution. I'm not sure if this is different for other versions of Laravel but I had to actually specify the method to be called.

```php
Route::fallback([\CodeZero\LocalizedRoutes\Controller\FallbackController::class, '__invoke'])
    ->middleware(\CodeZero\LocalizedRoutes\Middleware\SetLocale::class);
```

**Comment by ivanvermeyen** [comment]
Hi, I'm not sure why this would not work. I think Laravel 8 should support invokable controllers...
Any chance you can provide a failing test so I can debug?
Some examples: https://github.com/codezero-be/laravel-localized-routes/blob/master/tests/Unit/RedirectToLocalizedTest.php

**Comment by liam-milbel** [comment]
I'm unable to reproduce this in any tests. Tests all work which to me indicates there is something else interfering.

**Comment by ivanvermeyen** [comment]
I've been digging through the Laravel source code and found no reason why `__invoke` should not work...
Very bizar.

Since there is nothing I can really do to resolve this on my end, I will close this for now.
Feel free to reopen if needed.
If you find out what's wrong, I'm very curious :)
