### ISSUE TITLE
Route Translation not working on production

### ISSUE THREAD

**Issue by IgordeOliveira** [codezero-be/laravel-localized-routes#7]
On the navbar of my project I have the following button:

<a class="dropdown-item" href="{{ route(Route::current()->getName(),[],true,'en') }}">

Expected behavior:
- Send user to the english (en) localized version of the same page

What is happening:
- The code works just fine on local but not in production. Instead it shows the link to the same page on the current locale

**Comment by ivanvermeyen** [comment]
Hi,

Are you using the latest version?
Under the hood I'm using 0.0.0/composer-include-files 1.5 now.
The original composer-include-files stopped working.
Perhaps a composer update will fix it?

If not, can you share some specifics?

**Comment by IgordeOliveira** [comment]
I'm using "^ 1.3" version, I found another solution, but the weird one works fine on localhost, and when I go up to production (using the same dockerfile I use in localhost) the route helper does not modify the language of the current route

**Comment by ivanvermeyen** [comment]
That is weird yes... How did you manage to solve it?
