### ISSUE TITLE
auto redirect

### ISSUE THREAD

**Issue by cod3rshotout** [codezero-be/laravel-localized-routes#85]
Hi, this is just a question not an issue .. I'm not sure how to do this. Essentially I have this old url: `https://example.com/hello-world`, that now is in 404, is there a way that if the locale prefix is not specified then the url will go directly on `https://example.com/en/hello-world`?

Let me know, thanks in advance

**Comment by cod3rshotout** [comment]
> ```
> FallbackController
> ```

Hi, thanks for the quick reply. I already did this, but for some reason the route isn't redirected

**Comment by ivanvermeyen** [comment]
Does the fallback route have the middleware applied?
If not, it will use the app locale to generate a localized URL.
And is the `hello-world` route registered with the locale slug?

Maybe it's a combination of settings...
Can you compare with these tests?

https://github.com/codezero-be/laravel-localized-routes/blob/2.x/tests/Unit/RedirectToLocalizedTest.php

**Comment by cod3rshotout** [comment]
> Does the fallback route have the middleware applied? If not, it will use the app locale to generate a localized URL. And is the `hello-world` route registered with the locale slug?
> 
> Maybe it's a combination of settings... Can you compare with these tests?
> 
> https://github.com/codezero-be/laravel-localized-routes/blob/2.x/tests/Unit/RedirectToLocalizedTest.php

Yes, the middleware was applied. Actuallly the `SetLocale` middleware is correctly invoked but if I print the `$locale` variable from `handle` method of the middleware I get `null`.
