### ISSUE TITLE
How to get the current URL in a different locale?

### ISSUE THREAD

**Issue by ikkosatrio** [codezero-be/laravel-localized-routes#9]
i already add all my route to Route::localized, and when i access to main route ('/'). it's not found. also on all of my route notfound 
![image](https://user-images.githubusercontent.com/17069028/63633861-26742880-c679-11e9-9fb6-612344de2147.png)

**Comment by ikkosatrio** [comment]
sorry it't work now :).
now, how to get my current locale?.

**Comment by ivanvermeyen** [comment]
Hi,

You can find the active locale with `app()->getLocale()`.

I also wrote this package to find and set the user preferred locale when they visit a page:
https://github.com/codezero-be/laravel-localizer

**Comment by ikkosatrio** [comment]
how can i switch language on view ?

**Comment by ivanvermeyen** [comment]
This should work:

```php
$english = route('home', [], true, 'en');
$dutch = route('home', [], true, 'nl');
```

**Comment by ikkosatrio** [comment]
it will redirect to home route right?. how about switch the language on current route ?

**Comment by ivanvermeyen** [comment]
I created a macro for this...
In the `AppServiceProvider` (or any ServiceProvider you want) I added the macro:

```php
public function boot()
{
    \Route::macro('currentUrl', function ($locale = null) {
        return route(\Route::currentRouteName(), \Route::current()->parameters(), true, $locale);
    });
}
```

Then I can use it like this:

```php
$current = \Route::currentUrl();
$english = \Route::currentUrl('en');
$dutch = \Route::currentUrl('nl');
```

**Comment by ikkosatrio** [comment]
ok it work, thx a lot :)

**Comment by alishanster** [comment]
Hello! 
Sorry for writing it here, it seemed that my issue is related to this one. 
I added the macro in app service provider, however when I try to add the switcher on blade view, it gives me error `Route [] not defined. ` on any laravel routes (ex. example.com/en or example.com/en/terms), however works fine on Vue routes ( example.com/en/dashboard, where dashboard is vue SAP route)
Thank you

**Comment by ivanvermeyen** [comment]
Hi,

That example requires named routes.

But at some point I added a similar macro to this package that also handles unnamed routes:
https://github.com/codezero-be/laravel-localized-routes#%EF%B8%8F-generate-localized-versions-of-the-current-url

So you should be able to call `Route::localizedUrl($locale)` instead.

As an example, my own switcher looks something like this:

```php
@foreach(config('localized-routes.supported-locales') as $locale)
    @if ( ! App::isLocale($locale))
        <a href="{{ Route::localizedUrl($locale) }}">{{ strtoupper($locale) }}</a>
    @endif
@endforeach
```

This will generate links to alternate languages except the current one.

**Comment by ferdousanam** [comment]
> Hi,
> 
> That example requires named routes.
> 
> But at some point I added a similar macro to this package that also handles unnamed routes: https://github.com/codezero-be/laravel-localized-routes#%EF%B8%8F-generate-localized-versions-of-the-current-url
> 
> So you should be able to call `Route::localizedUrl($locale)` instead.
> 
> As an example, my own switcher looks something like this:
> 
> ```
> @foreach(config('localized-routes.supported-locales') as $locale)
>     @if ( ! App::isLocale($locale))
>         <a href="{{ Route::localizedUrl($locale) }}">{{ strtoupper($locale) }}</a>
>     @endif
> @endforeach
> ```
> 
> This will generate links to alternate languages except the current one.

This is not working. I have tried it.
