### ISSUE TITLE
Call to a member function getAction() on null

### ISSUE THREAD

**Issue by vincent-tarrit** [codezero-be/laravel-localized-routes#96]
Hello, I have issue that my $request->route() is null in the file Middleware/Detectors/ RouteActionDetector.php:36

Could you help me ?  

Thank you very much !

**Comment by vincent-tarrit** [comment]
To add details, the Route::localized is not recognized by PhpStorm...

**Comment by ivanvermeyen** [comment]
Hello,

Thanks for reporting the issue.
This is probably caused by [this line of code](https://github.com/codezero-be/laravel-localized-routes/blob/fac6e4a7bb32e2c42bb7aca53d3336d450ab3cba/src/Middleware/Detectors/RouteActionDetector.php#L36).

However, I can't reproduce the issue in a test.
Does it fail on a specific route?

**Comment by ivanvermeyen** [comment]
> To add details, the Route::localized is not recognized by PhpStorm...

PhpStorm should autocomplete this if you use https://github.com/barryvdh/laravel-ide-helper.

<img width="647" alt="Scherm­afbeelding 2023-05-18 om 12 51 13" src="https://github.com/codezero-be/laravel-localized-routes/assets/3598622/f4e15625-f221-4a47-bb68-4763d9b859b2">

I have this in my `scripts` section of `composer.json`:

```json

        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "@php artisan ide-helper:generate",
            "@php artisan ide-helper:meta"
        ]
```

**Comment by vincent-tarrit** [comment]
Hello, sorry ... I was not very wake up... I put the middleware in wrong array oups... everything works perfectly! Thank you !

**Comment by ivanvermeyen** [comment]
No worries, glad it works :)
